version: '3.7'
services:

    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
        restart: on-failure:3 
    web:
        build:
            context: ./server
        container_name: mini_bank_gunicorn
        restart: on-failure:3 
        expose:
             - 8000

