version: '3.7'
services:

    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web

    web:
        build:
            context: ./server
        container_name: mini_bank_gunicorn
        restart: "always"
        expose:
             - 8000

