version: '3.7'
services:
    postgres:
        image: postgres:11
        ports:
          - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: on-failure:3
        networks:
            internal:

    web:
        build:
            context: ./server
        container_name: mini_bank_gunicorn
        restart: on-failure:3 
        depends_on:
             - postgres
        expose:
             - 8000
        networks:
            default:
            internal:

    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
            - postgres
        restart: on-failure:3
        networks:
            default:
            internal:
    
networks:
    default:
    internal:
        internal: true
